### ISSUE TITLE
BFW001-60  -  Vimeo - Validate Url : Unable to validate Channel feed Url

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/vimeoPlugin#13]
Priority: Critical
Reproducibility: Always
Device / OS / Browser / Version: Windows 7 Home Premium / IE 11

ACTUAL RESULTS:- 
Valid Vimeo Channel feed url link is not validated successfully. An error appears Please try again. 

EXPECTED RESULTS: 
A valid channel feed url link is validated successfully. 

OTHER NOTES / ERROR MESSAGES:- 

username: gattesteracc_16@mailinator.com password: test1234 

http://bugs8.gatserver.com/uploads/3ddf151a7d53b8a9970a1a37d1609344.jpg

Steps to reproduce this issue
1.Open the site link  and login credentials
2. On the left menu, click on Plugin
3. Under Plugin, click on Active Plugin
4. On the list of created plugins, select on Vimeo Plugin then click on Edit
5. On Content Type, select Channel Feed
6. On the text box for URL, enter the valid vimeo channel feed url
7. Click on Validate ( error appears, the url is not successfully validated.)

**Comment by ianblair44** [comment]
Feed works now.
