### ISSUE TITLE
BFW001-61  -  MediaGallery: Insert selection button is already in active state although there is not image uploaded or selected yet

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/vimeoPlugin#14]
Priority: Low
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 /Chrome

ACTUAL RESULTS:- 
Insert selection button is already in active state although there is not image uploaded or selected yet 

EXPECTED RESULTS: 
Should not be active state yet, because there is not image uploaded or selected yet. 

OTHER NOTES / ERROR MESSAGES:- 

Desktop resolution is 1366x768 

username:gattesteracc_06@mailinator.com pass:test1234 

http://bugs8.gatserver.com/uploads/c4348d183b3b9e748b65715d9452074e.JPG 

http://bugs8.gatserver.com/uploads/9f38475289e928611efab7cf05bf6652.log

Steps to reproduce this issue
1. Log in and add all the plug in that is inscope.
2. On edit screen click add image for the media gallery window to display.
3. Do not upload or select image yet.
4. Notice that Insert selection button is already in active state even there is no image uploaded or select yet.

**Comment by ianblair44** [comment]
Moved to CS tickets.
