### ISSUE TITLE
BFW001-63  -  Vimeo - Design: Selected layout design goes back to default selection when switching tabs

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/vimeoPlugin#15]
Priority: Medium
Reproducibility: Always
Device / OS / Browser / Version: Windows 8 /Chrome

ACTUAL RESULTS:- 
Selected layout design goes back to default selection when switching tabs 

EXPECTED RESULTS: 
Should not go back to default selection when switching tabs. 

OTHER NOTES / ERROR MESSAGES:- 
Note that this only happens in vimeo plugin. 

Desktop resolution 1366x768

username:gattesteracc_06@mailinator.com pass:test1234 

http://bugs8.gatserver.com/uploads/d9c777310dddc66d01e7dead1cc3f382.mp4 

http://bugs8.gatserver.com/uploads/68031c6f6a8623a3b16e7c0a48eb688d.log

Steps to reproduce this issue
1. Log in and add all the plug in that is inscope.
2. Make Modification on your vimeo plug in.
3. On the design tab select a layout design.
4. Upon select a layout design go back to contents tab.
5. Then go back again to design tab.
6. Notice that selected layout design goes back to default selection.

**Comment by sandeepchhapola** [comment]
@ianblair44 its working fine.

Note:
we have showed default layout image when there is no layout selected. So if any layout has selected, it saved to datastore. Next time when app loaded, its init function called to fetch saved data. it will be showed default image till the response awaited, once saved data received and there is saved layout then it will show saved lauyout image. So make sure your selected layout has been saved.

**Comment by sakshityagi** [comment]
@ianblair44 Working now. Please review and let us know if its still an issue.
