### ISSUE TITLE
BFW001-42  -  Test Case - All Plugins - Edit Action: Previous window will show after saving the changes

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/vimeoPlugin#16]
Priority: Medium
Reproducability: Always
Device / OS / Browser / Version: Windows 7 | Mozilla Firefox 40.0.3

ACTUAL RESULTS:- 
Previous window will show after saving the changes. After clicking 'save' button window will not close or no message is shown, but instead it shows the previous window with the old settings. 

EXPECTED RESULTS: 
After clicking 'Save' button previous window should not show, instead retain the current window and show a prompt or message that changes was successfully saved. 

OTHER NOTES / ERROR MESSAGES:- 

Screen resolution: 1366 x 788 

Browser: Mozilla Firefox 40.0.3 

Account: gattesteracc_14@mailinator.com / test1234 

http://bugs8.gatserver.com/uploads/f58707a9a205b2fb18b199adb3a5f0c9.mp4

Steps to reproduce this issue
1. Login to http://int2.myapp.buildfire.com/
2. Add any plugins
3. Add images on 'Image Carousel' option 
4. Select 'Add/Edit Action'
5. On edit mode, change any settings
6. Observe the behavior upon saving the changes
7. Notice that Previous window will show after saving the changes

**Comment by ianblair44** [comment]
Moved to CS tickets.
