### ISSUE TITLE
BFW001-53  -  Vimeo: Staffpicks URL cannot be validated

### ISSUE THREAD

**Issue by gatgithub** [BuildFire/vimeoPlugin#17]
Priority: Critical
Reproducibility: Always
Device / OS / Browser / Version: Windows 10, Chrome

ACTUAL RESULTS:- 
Pasting staffpicks URL cannot be validated regardless which content type you choose e.g. https://vimeo.com/channels/staffpicks/138036294 

EXPECTED RESULTS: 
staffpicks URL can be validated 

OTHER NOTES / ERROR MESSAGES:- 
Username: gattesteracc_11@mailinator.com  
password: test1234 

Screen resolution: 1600x900 

http://bugs8.gatserver.com/uploads/5176b28c38c6e7f13b9e1b14942e49e9.mp4 
http://bugs8.gatserver.com/uploads/07f03ce4ccef5876d729069e997fb39e.jpg

Steps to reproduce this issue
1. Open test site
2. Log in with credentials
3. Go to the plugins tab > Add Plugin - > Add Vimeo
4. Enter something for the plugin title
5. Paste url into the url field, e.g. https://vimeo.com/channels/staffpicks/138036294
6. Click validate button
7. Select the radio button for different content types and try to validate again.

**Comment by ianblair44** [comment]
This actually isn't an issue. The wrong URL was used. It should have been this. 

http://vimeo.com/channels/staffpicks

We are adding more information to make it more clear to the user.
