### ISSUE TITLE
CP VIMEO - Incorrect text 

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/vimeoPlugin#18]
“Having problems with your feed…” should be changed to show them how they should format the feed URLs

Let's use the following text (fill in the appropriate url for each):...

Channel Feed URL Format: [CHANNEL_FEED_URL_FORMAT]
User Feed URL Format: [USER_FEED_URL_FORMAT]
Single Video URL Format: [SINGLE_VIDEO_URL_FORMAT]

**Comment by sakshityagi** [comment]
@ianblair44 This is working fine. Please review and close the issue.
