### ISSUE TITLE
Landscape view

### ISSUE THREAD

**Issue by Hreacon** [BuildFire/vimeoPlugin#57]
I was told to create a ticket to figure out how to get Vimeo to play the video in landscape mode inside a plugin. Can you please point at where this plugin shows a video in landscape mode so I may review the code around it?
After installing the plugin and playing with it for a little I can't see where it plays in landscape mode.
Thanks for your time

**Comment by abuturla** [comment]
@Hreacon You can reference our open source [Vimeo plugin](https://github.com/BuildFire/vimeoPlugin). Once the video is playing, the video will play in landscape mode. It is essentially handled at the OS level. 

Hope this helps.

**Comment by Hreacon** [comment]
@abuturla
So it works on iOS because that OS handles it, but not on android because rotation is locked, correct?
My client and I are getting multiple answers from multiple people. Some say it's possible but I'm not seeing how it is and I appreciate your time to help straighten this out.

**Comment by abuturla** [comment]
@Hreacon It is handled differently on Android. You can click "View Source" to open the video, and it will use the Vimeo app, which supports landscape mode.

**Comment by Hreacon** [comment]
@abuturla Thank you very much.
